In [25]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
# Import the dataset
dataset = pd.read_csv('titanic_prediction.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [27]:
# Replace null values in Age and Fare column
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,2:])
X[:,2:] = imputer.transform(X[:,2:])

In [28]:
# Label encode the male and female values
# no need to encode y as its already in 0 and 1
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])

In [29]:
print(X)

[[3 1 34.5 7.8292]
 [3 0 47.0 7.0]
 [2 1 62.0 9.6875]
 ...
 [3 1 38.5 7.25]
 [3 1 30.272590361445783 8.05]
 [3 1 30.272590361445783 22.3583]]


In [30]:
# Split the dataset into testing and training
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [39]:
# Apply feature scaling on pclass, age and fare
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,0:] = sc.fit_transform(X_train[:,0:])

X_test[:,0:] = sc.fit_transform(X_test[:,0:])

In [40]:
# Train the model using SVC - as its a classification problem
from sklearn.svm import SVC
classifier = SVC(kernel='linear', gamma='auto')
classifier.fit(X_train, y_train)

SVC(gamma='auto', kernel='linear')

In [43]:
# Predict a result
print(classifier.predict(sc.transform([[3, 0, 47, 7]])))

[1]


In [44]:
# Predict the test set
y_pred = classifier.predict(X_test)

In [45]:
# Compare y_pred and y_test
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred)

[[71  0]
 [ 0 55]]


1.0